import React, { useState } from 'react';
import { View, Text, TouchableOpacity, ScrollView, StyleSheet, Linking } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BASE_URL } from '../api';
import { acceptCurrentTerms } from '../terms';

export default function TermsGateScreen({ onAccept }) {
  const [checked, setChecked] = useState(false);

  const handleContinue = async () => {
    await acceptCurrentTerms();
    onAccept();
  };

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.container}>
        <Text style={styles.title}>Before you start</Text>

        <View style={styles.card}>
          <Text style={styles.body}>
            Document Risk Analyzer gives general, automated information about a document —
            it is not legal advice, and using it does not create a lawyer-client relationship.
          </Text>
          <Text style={styles.body}>
            Analyses are generated by an AI model and can be incomplete or wrong. Always verify
            anything important with a licensed attorney before you rely on it.
          </Text>
        </View>

        <TouchableOpacity onPress={() => Linking.openURL(`${BASE_URL}/terms`)}>
          <Text style={styles.link}>Read the full Terms of Use →</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.checkboxRow}
          onPress={() => setChecked(c => !c)}
          activeOpacity={0.7}
        >
          <View style={[styles.checkbox, checked && styles.checkboxChecked]}>
            {checked && <Text style={styles.checkmark}>✓</Text>}
          </View>
          <Text style={styles.checkboxLabel}>
            I understand this app does not provide legal advice
          </Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={[styles.continueBtn, !checked && styles.continueBtnDisabled]}
          onPress={handleContinue}
          disabled={!checked}
        >
          <Text style={styles.continueBtnText}>Continue</Text>
        </TouchableOpacity>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  container: { flexGrow: 1, justifyContent: 'center', padding: 28 },
  title: { fontSize: 24, fontWeight: '700', color: '#111', marginBottom: 20, textAlign: 'center' },
  card: {
    backgroundColor: '#f5f5f5', borderRadius: 12, padding: 16, marginBottom: 16,
  },
  body: { fontSize: 14, color: '#333', lineHeight: 21, marginBottom: 12 },
  link: { fontSize: 14, color: '#2f6fd0', fontWeight: '500', marginBottom: 28, textAlign: 'center' },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 24 },
  checkbox: {
    width: 24, height: 24, borderRadius: 6, borderWidth: 1.5, borderColor: '#ccc',
    alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  checkboxChecked: { backgroundColor: '#111', borderColor: '#111' },
  checkmark: { color: '#fff', fontSize: 14, fontWeight: '700' },
  checkboxLabel: { flex: 1, fontSize: 14, color: '#111', fontWeight: '500' },
  continueBtn: { backgroundColor: '#111', borderRadius: 10, paddingVertical: 16, alignItems: 'center' },
  continueBtnDisabled: { backgroundColor: '#ccc' },
  continueBtnText: { color: '#fff', fontSize: 16, fontWeight: '600' },
});
